#!/usr/bin/env python3
"""Build a hash-checked, explicit SDK-compatible derivative of pinned ROS types.

The fetched packages are read-only inputs. No network, SDK imports, or DDS
participants are involved. --check validates both inputs and generated bytes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
import tempfile

from fetch_assets import destination, valid
from fetch_unitree import check_manifest

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PREFIX = "ros_ws/src/unitree/"
PATCHES = {
    "unitree_api/msg/Response.msg": (b"int8[] binary", b"uint8[] binary"),
}


def expected_files(root: Path, manifest: dict) -> dict[str, bytes]:
    check_manifest(manifest)
    entries = [entry for entry in manifest["files"] if entry["path"].startswith(SOURCE_PREFIX)]
    if not entries:
        raise ValueError("Unitree lock contains no ROS package inputs")
    result = {}
    for entry in entries:
        source = destination(root, entry["path"])
        if source.is_symlink() or not valid(source, entry):
            raise ValueError(f"Pinned source mismatch: {entry['path']}")
        relative = entry["path"][len(SOURCE_PREFIX):]
        data = source.read_bytes()
        if relative in PATCHES:
            old, new = PATCHES[relative]
            if data.count(old) != 1:
                raise ValueError(f"Compatibility patch does not match exactly once: {relative}")
            data = data.replace(old, new)
        result[relative] = data
    if not PATCHES.keys() <= result.keys():
        raise ValueError("Unitree lock is missing a compatibility patch input")
    provenance = {
        "schema_version": 1,
        "compatibility_profile": "wendy-g1-sdk2-python-v1",
        "source_commit": next(item["commit"] for item in manifest["archives"] if item["id"] == "unitree_ros2"),
        "sdk_commit": next(item["commit"] for item in manifest["archives"] if item["id"] == "unitree_sdk2_python"),
        "patches": list(PATCHES),
        "files": [{"path": name, "size": len(data), "sha256": hashlib.sha256(data).hexdigest()}
                  for name, data in sorted(result.items())],
    }
    result["wendy-compatibility.json"] = (json.dumps(provenance, indent=2) + "\n").encode()
    return result


def prepare(root: Path, output: Path, manifest: dict, *, check: bool = False) -> int:
    source_root = (root / SOURCE_PREFIX).resolve()
    if output.resolve().is_relative_to(source_root) or source_root.is_relative_to(output.resolve()):
        raise ValueError("Derived output must be separate from pinned source packages")
    expected = expected_files(root, manifest)  # Verify every input before any writes.
    for name in expected:
        destination(output, name)
    failures = []
    if output.exists():
        extras = {str(path.relative_to(output)) for path in output.rglob("*") if path.is_file()} - expected.keys()
        if extras:
            raise ValueError(f"Unexpected generated files: {sorted(extras)}")
    for name, data in expected.items():
        target = destination(output, name)
        if target.is_file() and not target.is_symlink() and target.read_bytes() == data:
            continue
        if check:
            failures.append(name)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(dir=target.parent, prefix=f".{target.name}.", delete=False) as stream:
                temporary = Path(stream.name)
                stream.write(data)
            temporary.chmod(0o644)
            temporary.replace(target)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
    if failures:
        print(f"Missing or changed derived files: {failures}", file=sys.stderr)
        return 1
    print(f"Verified {len(expected) - 1} pinned/derived ROS files and compatibility provenance in {output}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path, help="Default: ROOT/ros_ws/generated_unitree")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return prepare(args.root, args.output or args.root / "ros_ws/generated_unitree",
                   json.loads((args.root / "unitree.lock.json").read_text()), check=args.check)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError) as error:
        print(f"Unitree compatibility preparation failed: {error}", file=sys.stderr)
        sys.exit(1)
