#!/usr/bin/env python3
"""Vendor shared example I/O and pinned Unitree Request types into standalone builds."""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
APPS = ('patrol', 'roam', 'teleop', 'sensors')

def expected():
    files = {'go2_io.py': (ROOT / 'examples/common/go2_io.py').read_bytes()}
    pins = {entry['path']:entry['sha256'] for entry in json.loads((ROOT/'unitree.lock.json').read_text())['files']}
    names = ('Request', 'RequestHeader', 'RequestIdentity', 'RequestLease', 'RequestPolicy')
    for name in names:
        source = f'ros_ws/src/unitree/unitree_api/msg/{name}.msg'
        data = (ROOT/source).read_bytes()
        if hashlib.sha256(data).hexdigest() != pins[source]:
            raise ValueError(f'Pinned Unitree source changed: {source}')
        files[f'unitree_api/msg/{name}.msg'] = data
    files['unitree_api/CMakeLists.txt'] = ('''cmake_minimum_required(VERSION 3.8)
project(unitree_api)
find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
rosidl_generate_interfaces(${PROJECT_NAME}
''' + ''.join(f'  "msg/{name}.msg"\n' for name in names) + ''')
ament_export_dependencies(rosidl_default_runtime)
ament_package()
''').encode()
    files['unitree_api/package.xml'] = b'''<?xml version="1.0"?>
<package format="3">
  <name>unitree_api</name><version>0.0.0</version>
  <description>Pinned Unitree sport request messages for Wendy examples.</description>
  <maintainer email="support@wendy.dev">Wendy</maintainer><license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
  <export><build_type>ament_cmake</build_type></export>
</package>
'''
    files['unitree_api/LICENSE'] = (ROOT / 'licenses/unitree_ros2.LICENSE').read_bytes()
    files['unitree_api/UPSTREAM.md'] = b'''Request definitions copied verbatim from unitreerobotics/unitree_ros2 commit
668d1ec5a05d1c38d3306bdca7d59f2ba3581a88, pinned by unitree.lock.json.
Only the five Request types needed for Move are built. No generated Response
or SportModeState types are substituted for the full simulator overlay.
Generated by tools/sync_examples.py; edit shared I/O in examples/common.
'''
    return files

def sync(check=False):
    mismatches=[]
    for app in APPS:
        for name, data in expected().items():
            if app == 'sensors' and name.startswith('unitree_api/'):
                continue
            target=ROOT/'examples'/app/name
            if target.exists() and target.read_bytes()==data:
                continue
            mismatches.append(str(target.relative_to(ROOT)))
            if not check:
                target.parent.mkdir(parents=True,exist_ok=True)
                target.write_bytes(data)
    if check and mismatches:
        print('Example dependencies differ: ' + ', '.join(mismatches), file=sys.stderr)
        return 1
    return 0

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    sys.exit(sync(parser.parse_args().check))
