// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: wendy/agent/services/v2/device_info_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

public import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Wendy_Agent_Services_V2_GetDeviceInfoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V2_GetDeviceInfoResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: String {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var osVersion: String {
    get {_storage._osVersion ?? String()}
    set {_uniqueStorage()._osVersion = newValue}
  }
  /// Returns true if `osVersion` has been explicitly set.
  public var hasOsVersion: Bool {_storage._osVersion != nil}
  /// Clears the value of `osVersion`. Subsequent reads from it will return its default value.
  public mutating func clearOsVersion() {_uniqueStorage()._osVersion = nil}

  public var os: String {
    get {_storage._os}
    set {_uniqueStorage()._os = newValue}
  }

  public var cpuArchitecture: String {
    get {_storage._cpuArchitecture}
    set {_uniqueStorage()._cpuArchitecture = newValue}
  }

  public var publicKey: String {
    get {_storage._publicKey ?? String()}
    set {_uniqueStorage()._publicKey = newValue}
  }
  /// Returns true if `publicKey` has been explicitly set.
  public var hasPublicKey: Bool {_storage._publicKey != nil}
  /// Clears the value of `publicKey`. Subsequent reads from it will return its default value.
  public mutating func clearPublicKey() {_uniqueStorage()._publicKey = nil}

  public var featureset: [String] {
    get {_storage._featureset}
    set {_uniqueStorage()._featureset = newValue}
  }

  public var deviceType: String {
    get {_storage._deviceType ?? String()}
    set {_uniqueStorage()._deviceType = newValue}
  }
  /// Returns true if `deviceType` has been explicitly set.
  public var hasDeviceType: Bool {_storage._deviceType != nil}
  /// Clears the value of `deviceType`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceType() {_uniqueStorage()._deviceType = nil}

  public var hasGpu_p: Bool {
    get {_storage._hasGpu_p ?? false}
    set {_uniqueStorage()._hasGpu_p = newValue}
  }
  /// Returns true if `hasGpu_p` has been explicitly set.
  public var hasHasGpu_p: Bool {_storage._hasGpu_p != nil}
  /// Clears the value of `hasGpu_p`. Subsequent reads from it will return its default value.
  public mutating func clearHasGpu_p() {_uniqueStorage()._hasGpu_p = nil}

  public var gpuVendor: String {
    get {_storage._gpuVendor ?? String()}
    set {_uniqueStorage()._gpuVendor = newValue}
  }
  /// Returns true if `gpuVendor` has been explicitly set.
  public var hasGpuVendor: Bool {_storage._gpuVendor != nil}
  /// Clears the value of `gpuVendor`. Subsequent reads from it will return its default value.
  public mutating func clearGpuVendor() {_uniqueStorage()._gpuVendor = nil}

  public var jetpackVersion: String {
    get {_storage._jetpackVersion ?? String()}
    set {_uniqueStorage()._jetpackVersion = newValue}
  }
  /// Returns true if `jetpackVersion` has been explicitly set.
  public var hasJetpackVersion: Bool {_storage._jetpackVersion != nil}
  /// Clears the value of `jetpackVersion`. Subsequent reads from it will return its default value.
  public mutating func clearJetpackVersion() {_uniqueStorage()._jetpackVersion = nil}

  public var cudaVersion: String {
    get {_storage._cudaVersion ?? String()}
    set {_uniqueStorage()._cudaVersion = newValue}
  }
  /// Returns true if `cudaVersion` has been explicitly set.
  public var hasCudaVersion: Bool {_storage._cudaVersion != nil}
  /// Clears the value of `cudaVersion`. Subsequent reads from it will return its default value.
  public mutating func clearCudaVersion() {_uniqueStorage()._cudaVersion = nil}

  public var diskUsedBytes: Int64 {
    get {_storage._diskUsedBytes ?? 0}
    set {_uniqueStorage()._diskUsedBytes = newValue}
  }
  /// Returns true if `diskUsedBytes` has been explicitly set.
  public var hasDiskUsedBytes: Bool {_storage._diskUsedBytes != nil}
  /// Clears the value of `diskUsedBytes`. Subsequent reads from it will return its default value.
  public mutating func clearDiskUsedBytes() {_uniqueStorage()._diskUsedBytes = nil}

  public var diskTotalBytes: Int64 {
    get {_storage._diskTotalBytes ?? 0}
    set {_uniqueStorage()._diskTotalBytes = newValue}
  }
  /// Returns true if `diskTotalBytes` has been explicitly set.
  public var hasDiskTotalBytes: Bool {_storage._diskTotalBytes != nil}
  /// Clears the value of `diskTotalBytes`. Subsequent reads from it will return its default value.
  public mutating func clearDiskTotalBytes() {_uniqueStorage()._diskTotalBytes = nil}

  /// Usage for every real (disk-backed) filesystem mounted on the device. The
  /// root filesystem is included here as well; disk_used_bytes/disk_total_bytes
  /// are retained for backwards compatibility. Empty when the agent cannot
  /// enumerate mounts.
  public var partitions: [Wendy_Agent_Services_V2_DiskPartition] {
    get {_storage._partitions}
    set {_uniqueStorage()._partitions = newValue}
  }

  /// GPU architecture identifier. Format is vendor-specific (e.g. "sm_87" for NVIDIA).
  public var gpuArch: String {
    get {_storage._gpuArch ?? String()}
    set {_uniqueStorage()._gpuArch = newValue}
  }
  /// Returns true if `gpuArch` has been explicitly set.
  public var hasGpuArch: Bool {_storage._gpuArch != nil}
  /// Clears the value of `gpuArch`. Subsequent reads from it will return its default value.
  public mutating func clearGpuArch() {_uniqueStorage()._gpuArch = nil}

  /// Total physical memory (RAM) in bytes, from /proc/meminfo. Zero when the
  /// agent cannot read it (a real host never has 0 bytes of RAM).
  public var memTotalBytes: Int64 {
    get {_storage._memTotalBytes}
    set {_uniqueStorage()._memTotalBytes = newValue}
  }

  /// Number of online logical CPU cores, from /proc/stat. Zero when the
  /// agent cannot read it.
  public var cpuCount: UInt32 {
    get {_storage._cpuCount}
    set {_uniqueStorage()._cpuCount = newValue}
  }

  /// Filesystem containing /var/lib/containerd. Absent when inspection fails.
  /// 18-19 are reserved for the NPU fields landing alongside this change.
  public var containerStorage: Wendy_Agent_Services_V2_DiskPartition {
    get {_storage._containerStorage ?? Wendy_Agent_Services_V2_DiskPartition()}
    set {_uniqueStorage()._containerStorage = newValue}
  }
  /// Returns true if `containerStorage` has been explicitly set.
  public var hasContainerStorage: Bool {_storage._containerStorage != nil}
  /// Clears the value of `containerStorage`. Subsequent reads from it will return its default value.
  public mutating func clearContainerStorage() {_uniqueStorage()._containerStorage = nil}

  /// Empty means no supported compute backend detected; absent means older agent.
  public var gpuCapabilities: Wendy_Agent_Services_V2_GpuCapabilities {
    get {_storage._gpuCapabilities ?? Wendy_Agent_Services_V2_GpuCapabilities()}
    set {_uniqueStorage()._gpuCapabilities = newValue}
  }
  /// Returns true if `gpuCapabilities` has been explicitly set.
  public var hasGpuCapabilities: Bool {_storage._gpuCapabilities != nil}
  /// Clears the value of `gpuCapabilities`. Subsequent reads from it will return its default value.
  public mutating func clearGpuCapabilities() {_uniqueStorage()._gpuCapabilities = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Usage information for a single mounted filesystem.
public nonisolated struct Wendy_Agent_Services_V2_DiskPartition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Mount point (e.g. "/", "/boot", "/data").
  public var mountpoint: String = String()

  /// Filesystem type (e.g. "ext4", "vfat").
  public var filesystem: String = String()

  /// Backing block device (e.g. "/dev/mmcblk0p2").
  public var device: String = String()

  /// Bytes currently used on the filesystem.
  public var usedBytes: Int64 = 0

  /// Total bytes on the filesystem.
  public var totalBytes: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V2_ListHardwareCapabilitiesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var categoryFilter: String {
    get {_categoryFilter ?? String()}
    set {_categoryFilter = newValue}
  }
  /// Returns true if `categoryFilter` has been explicitly set.
  public var hasCategoryFilter: Bool {self._categoryFilter != nil}
  /// Clears the value of `categoryFilter`. Subsequent reads from it will return its default value.
  public mutating func clearCategoryFilter() {self._categoryFilter = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _categoryFilter: String? = nil
}

public nonisolated struct Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var capabilities: [Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse.HardwareCapability] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated struct HardwareCapability: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var category: String = String()

    public var devicePath: String = String()

    public var description_p: String = String()

    public var properties: Dictionary<String,String> = [:]

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V2_GpuCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Host compute backends an app can use: cuda, rocm, metal, or qnn (the
  /// Qualcomm Hexagon NPU reached over FastRPC, e.g. Dragonwing).
  public var computeBackends: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "wendy.agent.services.v2"

nonisolated extension Wendy_Agent_Services_V2_GetDeviceInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetDeviceInfoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_GetDeviceInfoRequest, rhs: Wendy_Agent_Services_V2_GetDeviceInfoRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_GetDeviceInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetDeviceInfoResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{3}os_version\0\u{1}os\0\u{3}cpu_architecture\0\u{3}public_key\0\u{1}featureset\0\u{3}device_type\0\u{3}has_gpu\0\u{3}gpu_vendor\0\u{3}jetpack_version\0\u{3}cuda_version\0\u{3}disk_used_bytes\0\u{3}disk_total_bytes\0\u{1}partitions\0\u{3}gpu_arch\0\u{3}mem_total_bytes\0\u{3}cpu_count\0\u{4}\u{3}container_storage\0\u{3}gpu_capabilities\0")

  fileprivate class _StorageClass {
    var _version: String = String()
    var _osVersion: String? = nil
    var _os: String = String()
    var _cpuArchitecture: String = String()
    var _publicKey: String? = nil
    var _featureset: [String] = []
    var _deviceType: String? = nil
    var _hasGpu_p: Bool? = nil
    var _gpuVendor: String? = nil
    var _jetpackVersion: String? = nil
    var _cudaVersion: String? = nil
    var _diskUsedBytes: Int64? = nil
    var _diskTotalBytes: Int64? = nil
    var _partitions: [Wendy_Agent_Services_V2_DiskPartition] = []
    var _gpuArch: String? = nil
    var _memTotalBytes: Int64 = 0
    var _cpuCount: UInt32 = 0
    var _containerStorage: Wendy_Agent_Services_V2_DiskPartition? = nil
    var _gpuCapabilities: Wendy_Agent_Services_V2_GpuCapabilities? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _osVersion = source._osVersion
      _os = source._os
      _cpuArchitecture = source._cpuArchitecture
      _publicKey = source._publicKey
      _featureset = source._featureset
      _deviceType = source._deviceType
      _hasGpu_p = source._hasGpu_p
      _gpuVendor = source._gpuVendor
      _jetpackVersion = source._jetpackVersion
      _cudaVersion = source._cudaVersion
      _diskUsedBytes = source._diskUsedBytes
      _diskTotalBytes = source._diskTotalBytes
      _partitions = source._partitions
      _gpuArch = source._gpuArch
      _memTotalBytes = source._memTotalBytes
      _cpuCount = source._cpuCount
      _containerStorage = source._containerStorage
      _gpuCapabilities = source._gpuCapabilities
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._version) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._osVersion) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._os) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._cpuArchitecture) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._publicKey) }()
        case 6: try { try decoder.decodeRepeatedStringField(value: &_storage._featureset) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._deviceType) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._hasGpu_p) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._gpuVendor) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._jetpackVersion) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._cudaVersion) }()
        case 12: try { try decoder.decodeSingularInt64Field(value: &_storage._diskUsedBytes) }()
        case 13: try { try decoder.decodeSingularInt64Field(value: &_storage._diskTotalBytes) }()
        case 14: try { try decoder.decodeRepeatedMessageField(value: &_storage._partitions) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._gpuArch) }()
        case 16: try { try decoder.decodeSingularInt64Field(value: &_storage._memTotalBytes) }()
        case 17: try { try decoder.decodeSingularUInt32Field(value: &_storage._cpuCount) }()
        case 20: try { try decoder.decodeSingularMessageField(value: &_storage._containerStorage) }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._gpuCapabilities) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._version.isEmpty {
        try visitor.visitSingularStringField(value: _storage._version, fieldNumber: 1)
      }
      try { if let v = _storage._osVersion {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      if !_storage._os.isEmpty {
        try visitor.visitSingularStringField(value: _storage._os, fieldNumber: 3)
      }
      if !_storage._cpuArchitecture.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cpuArchitecture, fieldNumber: 4)
      }
      try { if let v = _storage._publicKey {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      if !_storage._featureset.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._featureset, fieldNumber: 6)
      }
      try { if let v = _storage._deviceType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._hasGpu_p {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._gpuVendor {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._jetpackVersion {
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._cudaVersion {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._diskUsedBytes {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._diskTotalBytes {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 13)
      } }()
      if !_storage._partitions.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._partitions, fieldNumber: 14)
      }
      try { if let v = _storage._gpuArch {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      if _storage._memTotalBytes != 0 {
        try visitor.visitSingularInt64Field(value: _storage._memTotalBytes, fieldNumber: 16)
      }
      if _storage._cpuCount != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._cpuCount, fieldNumber: 17)
      }
      try { if let v = _storage._containerStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._gpuCapabilities {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_GetDeviceInfoResponse, rhs: Wendy_Agent_Services_V2_GetDeviceInfoResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._osVersion != rhs_storage._osVersion {return false}
        if _storage._os != rhs_storage._os {return false}
        if _storage._cpuArchitecture != rhs_storage._cpuArchitecture {return false}
        if _storage._publicKey != rhs_storage._publicKey {return false}
        if _storage._featureset != rhs_storage._featureset {return false}
        if _storage._deviceType != rhs_storage._deviceType {return false}
        if _storage._hasGpu_p != rhs_storage._hasGpu_p {return false}
        if _storage._gpuVendor != rhs_storage._gpuVendor {return false}
        if _storage._jetpackVersion != rhs_storage._jetpackVersion {return false}
        if _storage._cudaVersion != rhs_storage._cudaVersion {return false}
        if _storage._diskUsedBytes != rhs_storage._diskUsedBytes {return false}
        if _storage._diskTotalBytes != rhs_storage._diskTotalBytes {return false}
        if _storage._partitions != rhs_storage._partitions {return false}
        if _storage._gpuArch != rhs_storage._gpuArch {return false}
        if _storage._memTotalBytes != rhs_storage._memTotalBytes {return false}
        if _storage._cpuCount != rhs_storage._cpuCount {return false}
        if _storage._containerStorage != rhs_storage._containerStorage {return false}
        if _storage._gpuCapabilities != rhs_storage._gpuCapabilities {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_DiskPartition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DiskPartition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mountpoint\0\u{1}filesystem\0\u{1}device\0\u{3}used_bytes\0\u{3}total_bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mountpoint) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.filesystem) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.device) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.usedBytes) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.totalBytes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mountpoint.isEmpty {
      try visitor.visitSingularStringField(value: self.mountpoint, fieldNumber: 1)
    }
    if !self.filesystem.isEmpty {
      try visitor.visitSingularStringField(value: self.filesystem, fieldNumber: 2)
    }
    if !self.device.isEmpty {
      try visitor.visitSingularStringField(value: self.device, fieldNumber: 3)
    }
    if self.usedBytes != 0 {
      try visitor.visitSingularInt64Field(value: self.usedBytes, fieldNumber: 4)
    }
    if self.totalBytes != 0 {
      try visitor.visitSingularInt64Field(value: self.totalBytes, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_DiskPartition, rhs: Wendy_Agent_Services_V2_DiskPartition) -> Bool {
    if lhs.mountpoint != rhs.mountpoint {return false}
    if lhs.filesystem != rhs.filesystem {return false}
    if lhs.device != rhs.device {return false}
    if lhs.usedBytes != rhs.usedBytes {return false}
    if lhs.totalBytes != rhs.totalBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_ListHardwareCapabilitiesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListHardwareCapabilitiesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}category_filter\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._categoryFilter) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._categoryFilter {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_ListHardwareCapabilitiesRequest, rhs: Wendy_Agent_Services_V2_ListHardwareCapabilitiesRequest) -> Bool {
    if lhs._categoryFilter != rhs._categoryFilter {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListHardwareCapabilitiesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}capabilities\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.capabilities) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.capabilities.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.capabilities, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse, rhs: Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse) -> Bool {
    if lhs.capabilities != rhs.capabilities {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse.HardwareCapability: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse.protoMessageName + ".HardwareCapability"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}category\0\u{3}device_path\0\u{1}description\0\u{1}properties\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.category) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.devicePath) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.properties) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.category.isEmpty {
      try visitor.visitSingularStringField(value: self.category, fieldNumber: 1)
    }
    if !self.devicePath.isEmpty {
      try visitor.visitSingularStringField(value: self.devicePath, fieldNumber: 2)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 3)
    }
    if !self.properties.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.properties, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse.HardwareCapability, rhs: Wendy_Agent_Services_V2_ListHardwareCapabilitiesResponse.HardwareCapability) -> Bool {
    if lhs.category != rhs.category {return false}
    if lhs.devicePath != rhs.devicePath {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.properties != rhs.properties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_GpuCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GpuCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}compute_backends\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.computeBackends) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.computeBackends.isEmpty {
      try visitor.visitRepeatedStringField(value: self.computeBackends, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_GpuCapabilities, rhs: Wendy_Agent_Services_V2_GpuCapabilities) -> Bool {
    if lhs.computeBackends != rhs.computeBackends {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
