// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: wendy/agent/services/v2/local_mesh_admin_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

public import GRPCCore
public import GRPCProtobuf

// MARK: - wendy.agent.services.v2.WendyLocalMeshAdminService

/// Namespace containing generated types for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Wendy_Agent_Services_V2_WendyLocalMeshAdminService: Sendable {
    /// Service descriptor for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendy.agent.services.v2.WendyLocalMeshAdminService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "ConfigureLocalMesh" metadata.
        public enum ConfigureLocalMesh: Sendable {
            /// Request type for "ConfigureLocalMesh".
            public typealias Input = Wendy_Agent_Services_V2_ConfigureLocalMeshRequest
            /// Response type for "ConfigureLocalMesh".
            public typealias Output = Wendy_Agent_Services_V2_LocalMeshStatus
            /// Descriptor for "ConfigureLocalMesh".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendy.agent.services.v2.WendyLocalMeshAdminService"),
                method: "ConfigureLocalMesh",
                type: .unary
            )
        }
        /// Namespace for "GetLocalMeshStatus" metadata.
        public enum GetLocalMeshStatus: Sendable {
            /// Request type for "GetLocalMeshStatus".
            public typealias Input = Wendy_Agent_Services_V2_GetLocalMeshStatusRequest
            /// Response type for "GetLocalMeshStatus".
            public typealias Output = Wendy_Agent_Services_V2_LocalMeshStatus
            /// Descriptor for "GetLocalMeshStatus".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendy.agent.services.v2.WendyLocalMeshAdminService"),
                method: "GetLocalMeshStatus",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            ConfigureLocalMesh.descriptor,
            GetLocalMeshStatus.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    public static let wendy_agent_services_v2_WendyLocalMeshAdminService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendy.agent.services.v2.WendyLocalMeshAdminService")
}

// MARK: wendy.agent.services.v2.WendyLocalMeshAdminService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService {
    /// Streaming variant of the service protocol for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > User administration of an enrolled device's local mesh. Asset certificates
    /// > cannot change carrier or Internet-sharing policy.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ConfigureLocalMesh" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendy_Agent_Services_V2_LocalMeshStatus` messages.
        func configureLocalMesh(
            request: GRPCCore.StreamingServerRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus>

        /// Handle the "GetLocalMeshStatus" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendy_Agent_Services_V2_LocalMeshStatus` messages.
        func getLocalMeshStatus(
            request: GRPCCore.StreamingServerRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus>
    }

    /// Service protocol for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > User administration of an enrolled device's local mesh. Asset certificates
    /// > cannot change carrier or Internet-sharing policy.
    public protocol ServiceProtocol: Wendy_Agent_Services_V2_WendyLocalMeshAdminService.StreamingServiceProtocol {
        /// Handle the "ConfigureLocalMesh" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendy_Agent_Services_V2_LocalMeshStatus` message.
        func configureLocalMesh(
            request: GRPCCore.ServerRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus>

        /// Handle the "GetLocalMeshStatus" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendy_Agent_Services_V2_LocalMeshStatus` message.
        func getLocalMeshStatus(
            request: GRPCCore.ServerRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus>
    }

    /// Simple service protocol for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > User administration of an enrolled device's local mesh. Asset certificates
    /// > cannot change carrier or Internet-sharing policy.
    public protocol SimpleServiceProtocol: Wendy_Agent_Services_V2_WendyLocalMeshAdminService.ServiceProtocol {
        /// Handle the "ConfigureLocalMesh" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendy_Agent_Services_V2_LocalMeshStatus` to respond with.
        func configureLocalMesh(
            request: Wendy_Agent_Services_V2_ConfigureLocalMeshRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendy_Agent_Services_V2_LocalMeshStatus

        /// Handle the "GetLocalMeshStatus" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendy_Agent_Services_V2_LocalMeshStatus` to respond with.
        func getLocalMeshStatus(
            request: Wendy_Agent_Services_V2_GetLocalMeshStatusRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendy_Agent_Services_V2_LocalMeshStatus
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Wendy_Agent_Services_V2_WendyLocalMeshAdminService.Method.ConfigureLocalMesh.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendy_Agent_Services_V2_LocalMeshStatus>(),
            handler: { request, context in
                try await self.configureLocalMesh(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Wendy_Agent_Services_V2_WendyLocalMeshAdminService.Method.GetLocalMeshStatus.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendy_Agent_Services_V2_LocalMeshStatus>(),
            handler: { request, context in
                try await self.getLocalMeshStatus(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService.ServiceProtocol {
    public func configureLocalMesh(
        request: GRPCCore.StreamingServerRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus> {
        let response = try await self.configureLocalMesh(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func getLocalMeshStatus(
        request: GRPCCore.StreamingServerRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus> {
        let response = try await self.getLocalMeshStatus(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService.SimpleServiceProtocol {
    public func configureLocalMesh(
        request: GRPCCore.ServerRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus> {
        return GRPCCore.ServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus>(
            message: try await self.configureLocalMesh(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func getLocalMeshStatus(
        request: GRPCCore.ServerRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus> {
        return GRPCCore.ServerResponse<Wendy_Agent_Services_V2_LocalMeshStatus>(
            message: try await self.getLocalMeshStatus(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: wendy.agent.services.v2.WendyLocalMeshAdminService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService {
    /// Generated client protocol for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > User administration of an enrolled device's local mesh. Asset certificates
    /// > cannot change carrier or Internet-sharing policy.
    public protocol ClientProtocol: Sendable {
        /// Call the "ConfigureLocalMesh" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` message.
        ///   - serializer: A serializer for `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` messages.
        ///   - deserializer: A deserializer for `Wendy_Agent_Services_V2_LocalMeshStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func configureLocalMesh<Result>(
            request: GRPCCore.ClientRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendy_Agent_Services_V2_LocalMeshStatus>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetLocalMeshStatus" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` message.
        ///   - serializer: A serializer for `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` messages.
        ///   - deserializer: A deserializer for `Wendy_Agent_Services_V2_LocalMeshStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getLocalMeshStatus<Result>(
            request: GRPCCore.ClientRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendy_Agent_Services_V2_LocalMeshStatus>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "wendy.agent.services.v2.WendyLocalMeshAdminService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > User administration of an enrolled device's local mesh. Asset certificates
    /// > cannot change carrier or Internet-sharing policy.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ConfigureLocalMesh" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` message.
        ///   - serializer: A serializer for `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` messages.
        ///   - deserializer: A deserializer for `Wendy_Agent_Services_V2_LocalMeshStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func configureLocalMesh<Result>(
            request: GRPCCore.ClientRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendy_Agent_Services_V2_LocalMeshStatus>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendy_Agent_Services_V2_WendyLocalMeshAdminService.Method.ConfigureLocalMesh.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetLocalMeshStatus" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` message.
        ///   - serializer: A serializer for `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` messages.
        ///   - deserializer: A deserializer for `Wendy_Agent_Services_V2_LocalMeshStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getLocalMeshStatus<Result>(
            request: GRPCCore.ClientRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendy_Agent_Services_V2_LocalMeshStatus>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendy_Agent_Services_V2_WendyLocalMeshAdminService.Method.GetLocalMeshStatus.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService.ClientProtocol {
    /// Call the "ConfigureLocalMesh" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendy_Agent_Services_V2_ConfigureLocalMeshRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func configureLocalMesh<Result>(
        request: GRPCCore.ClientRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.configureLocalMesh(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendy_Agent_Services_V2_LocalMeshStatus>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetLocalMeshStatus" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendy_Agent_Services_V2_GetLocalMeshStatusRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLocalMeshStatus<Result>(
        request: GRPCCore.ClientRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getLocalMeshStatus(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendy_Agent_Services_V2_LocalMeshStatus>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendy_Agent_Services_V2_WendyLocalMeshAdminService.ClientProtocol {
    /// Call the "ConfigureLocalMesh" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func configureLocalMesh<Result>(
        _ message: Wendy_Agent_Services_V2_ConfigureLocalMeshRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendy_Agent_Services_V2_ConfigureLocalMeshRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.configureLocalMesh(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetLocalMeshStatus" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLocalMeshStatus<Result>(
        _ message: Wendy_Agent_Services_V2_GetLocalMeshStatusRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendy_Agent_Services_V2_LocalMeshStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendy_Agent_Services_V2_GetLocalMeshStatusRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getLocalMeshStatus(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}
