// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: wendy/agent/services/v2/local_mesh_admin_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

public import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Wendy_Agent_Services_V2_ConfigureLocalMeshRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Presence means update; omitted fields preserve the saved value.
  public var participate: Bool {
    get {_participate ?? false}
    set {_participate = newValue}
  }
  /// Returns true if `participate` has been explicitly set.
  public var hasParticipate: Bool {self._participate != nil}
  /// Clears the value of `participate`. Subsequent reads from it will return its default value.
  public mutating func clearParticipate() {self._participate = nil}

  public var roam: Bool {
    get {_roam ?? false}
    set {_roam = newValue}
  }
  /// Returns true if `roam` has been explicitly set.
  public var hasRoam: Bool {self._roam != nil}
  /// Clears the value of `roam`. Subsequent reads from it will return its default value.
  public mutating func clearRoam() {self._roam = nil}

  public var shareUplink: Bool {
    get {_shareUplink ?? false}
    set {_shareUplink = newValue}
  }
  /// Returns true if `shareUplink` has been explicitly set.
  public var hasShareUplink: Bool {self._shareUplink != nil}
  /// Clears the value of `shareUplink`. Subsequent reads from it will return its default value.
  public mutating func clearShareUplink() {self._shareUplink = nil}

  public var nan: Bool {
    get {_nan ?? false}
    set {_nan = newValue}
  }
  /// Returns true if `nan` has been explicitly set.
  public var hasNan: Bool {self._nan != nil}
  /// Clears the value of `nan`. Subsequent reads from it will return its default value.
  public mutating func clearNan() {self._nan = nil}

  public var ble: Bool {
    get {_ble ?? false}
    set {_ble = newValue}
  }
  /// Returns true if `ble` has been explicitly set.
  public var hasBle: Bool {self._ble != nil}
  /// Clears the value of `ble`. Subsequent reads from it will return its default value.
  public mutating func clearBle() {self._ble = nil}

  public var ethernet: Bool {
    get {_ethernet ?? false}
    set {_ethernet = newValue}
  }
  /// Returns true if `ethernet` has been explicitly set.
  public var hasEthernet: Bool {self._ethernet != nil}
  /// Clears the value of `ethernet`. Subsequent reads from it will return its default value.
  public mutating func clearEthernet() {self._ethernet = nil}

  public var infrastructureWifi: Bool {
    get {_infrastructureWifi ?? false}
    set {_infrastructureWifi = newValue}
  }
  /// Returns true if `infrastructureWifi` has been explicitly set.
  public var hasInfrastructureWifi: Bool {self._infrastructureWifi != nil}
  /// Clears the value of `infrastructureWifi`. Subsequent reads from it will return its default value.
  public mutating func clearInfrastructureWifi() {self._infrastructureWifi = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _participate: Bool? = nil
  fileprivate var _roam: Bool? = nil
  fileprivate var _shareUplink: Bool? = nil
  fileprivate var _nan: Bool? = nil
  fileprivate var _ble: Bool? = nil
  fileprivate var _ethernet: Bool? = nil
  fileprivate var _infrastructureWifi: Bool? = nil
}

public nonisolated struct Wendy_Agent_Services_V2_GetLocalMeshStatusRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V2_LocalMeshConfiguration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var participate: Bool = false

  public var roam: Bool = false

  public var shareUplink: Bool = false

  public var nan: Bool = false

  public var ble: Bool = false

  public var tcpListen: String = String()

  public var configuredTcpPeers: UInt32 = 0

  public var ethernet: Bool = false

  public var infrastructureWifi: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V2_LocalMeshStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var configured: Wendy_Agent_Services_V2_LocalMeshConfiguration {
    get {_configured ?? Wendy_Agent_Services_V2_LocalMeshConfiguration()}
    set {_configured = newValue}
  }
  /// Returns true if `configured` has been explicitly set.
  public var hasConfigured: Bool {self._configured != nil}
  /// Clears the value of `configured`. Subsequent reads from it will return its default value.
  public mutating func clearConfigured() {self._configured = nil}

  /// Persisted intent is not proof that radios, routes or a donor are healthy.
  public var runtimeAvailable: Bool = false

  public var state: String = String()

  public var detail: String = String()

  public var authenticatedPeers: UInt32 = 0

  public var gatewayAssetID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _configured: Wendy_Agent_Services_V2_LocalMeshConfiguration? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "wendy.agent.services.v2"

nonisolated extension Wendy_Agent_Services_V2_ConfigureLocalMeshRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConfigureLocalMeshRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}participate\0\u{1}roam\0\u{3}share_uplink\0\u{1}nan\0\u{1}ble\0\u{1}ethernet\0\u{3}infrastructure_wifi\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._participate) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._roam) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._shareUplink) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._nan) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._ble) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._ethernet) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._infrastructureWifi) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._participate {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._roam {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._shareUplink {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._nan {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._ble {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._ethernet {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._infrastructureWifi {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_ConfigureLocalMeshRequest, rhs: Wendy_Agent_Services_V2_ConfigureLocalMeshRequest) -> Bool {
    if lhs._participate != rhs._participate {return false}
    if lhs._roam != rhs._roam {return false}
    if lhs._shareUplink != rhs._shareUplink {return false}
    if lhs._nan != rhs._nan {return false}
    if lhs._ble != rhs._ble {return false}
    if lhs._ethernet != rhs._ethernet {return false}
    if lhs._infrastructureWifi != rhs._infrastructureWifi {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_GetLocalMeshStatusRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetLocalMeshStatusRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_GetLocalMeshStatusRequest, rhs: Wendy_Agent_Services_V2_GetLocalMeshStatusRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_LocalMeshConfiguration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LocalMeshConfiguration"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}participate\0\u{1}roam\0\u{3}share_uplink\0\u{1}nan\0\u{1}ble\0\u{3}tcp_listen\0\u{3}configured_tcp_peers\0\u{1}ethernet\0\u{3}infrastructure_wifi\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.participate) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.roam) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.shareUplink) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.nan) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.ble) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.tcpListen) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.configuredTcpPeers) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.ethernet) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.infrastructureWifi) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.participate != false {
      try visitor.visitSingularBoolField(value: self.participate, fieldNumber: 1)
    }
    if self.roam != false {
      try visitor.visitSingularBoolField(value: self.roam, fieldNumber: 2)
    }
    if self.shareUplink != false {
      try visitor.visitSingularBoolField(value: self.shareUplink, fieldNumber: 3)
    }
    if self.nan != false {
      try visitor.visitSingularBoolField(value: self.nan, fieldNumber: 4)
    }
    if self.ble != false {
      try visitor.visitSingularBoolField(value: self.ble, fieldNumber: 5)
    }
    if !self.tcpListen.isEmpty {
      try visitor.visitSingularStringField(value: self.tcpListen, fieldNumber: 6)
    }
    if self.configuredTcpPeers != 0 {
      try visitor.visitSingularUInt32Field(value: self.configuredTcpPeers, fieldNumber: 7)
    }
    if self.ethernet != false {
      try visitor.visitSingularBoolField(value: self.ethernet, fieldNumber: 8)
    }
    if self.infrastructureWifi != false {
      try visitor.visitSingularBoolField(value: self.infrastructureWifi, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_LocalMeshConfiguration, rhs: Wendy_Agent_Services_V2_LocalMeshConfiguration) -> Bool {
    if lhs.participate != rhs.participate {return false}
    if lhs.roam != rhs.roam {return false}
    if lhs.shareUplink != rhs.shareUplink {return false}
    if lhs.nan != rhs.nan {return false}
    if lhs.ble != rhs.ble {return false}
    if lhs.tcpListen != rhs.tcpListen {return false}
    if lhs.configuredTcpPeers != rhs.configuredTcpPeers {return false}
    if lhs.ethernet != rhs.ethernet {return false}
    if lhs.infrastructureWifi != rhs.infrastructureWifi {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V2_LocalMeshStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LocalMeshStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}configured\0\u{3}runtime_available\0\u{1}state\0\u{1}detail\0\u{3}authenticated_peers\0\u{3}gateway_asset_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._configured) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.runtimeAvailable) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.detail) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.authenticatedPeers) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.gatewayAssetID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._configured {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.runtimeAvailable != false {
      try visitor.visitSingularBoolField(value: self.runtimeAvailable, fieldNumber: 2)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 3)
    }
    if !self.detail.isEmpty {
      try visitor.visitSingularStringField(value: self.detail, fieldNumber: 4)
    }
    if self.authenticatedPeers != 0 {
      try visitor.visitSingularUInt32Field(value: self.authenticatedPeers, fieldNumber: 5)
    }
    if self.gatewayAssetID != 0 {
      try visitor.visitSingularInt32Field(value: self.gatewayAssetID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V2_LocalMeshStatus, rhs: Wendy_Agent_Services_V2_LocalMeshStatus) -> Bool {
    if lhs._configured != rhs._configured {return false}
    if lhs.runtimeAvailable != rhs.runtimeAvailable {return false}
    if lhs.state != rhs.state {return false}
    if lhs.detail != rhs.detail {return false}
    if lhs.authenticatedPeers != rhs.authenticatedPeers {return false}
    if lhs.gatewayAssetID != rhs.gatewayAssetID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
