cmake_minimum_required(VERSION 3.8)
project(r2_command_ingress)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
add_executable(r2_command_ingress src/command_ingress.cpp)
target_compile_features(r2_command_ingress PUBLIC cxx_std_17)
ament_target_dependencies(r2_command_ingress rclcpp geometry_msgs)
install(TARGETS r2_command_ingress DESTINATION lib/${PROJECT_NAME})
ament_package()
