# qemu-arm64: QEMU aarch64 virtual machine

require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/local/common.inc
require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/local/qemu.inc

MACHINE = "qemuarm64-wendyos"

# QEMU rootfs size in KB (used by qemu-image.inc):
#   1048576 = 1GB, 2097152 = 2GB, 4194304 = 4GB (default)
QEMU_ROOTFS_SIZE = "4194304"
