POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
    ${TOPDIR}/../repos/meta-openembedded/meta-filesystems \
    ${TOPDIR}/../repos/meta-openembedded/meta-multimedia \
    ${TOPDIR}/../repos/meta-openembedded/meta-networking \
    ${TOPDIR}/../repos/meta-openembedded/meta-oe \
    ${TOPDIR}/../repos/meta-openembedded/meta-python \
    ${TOPDIR}/../repos/meta-virtualization \
    ${TOPDIR}/../repos/meta-raspberrypi \
    ${TOPDIR}/../repos/poky/meta \
    ${TOPDIR}/../repos/poky/meta-poky \
    ${TOPDIR}/../repos/poky/meta-yocto-bsp \
    ${TOPDIR}/../%META-REPO% \
    ${TOPDIR}/../%META-REPO%/meta-rpi-extensions \
    "
