// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: wendy/agent/services/v1/wendy_agent_v1_video_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
public import FoundationEssentials
#else
public import Foundation
#endif
public import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Wendy_Agent_Services_V1_VideoTransport: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case usb // = 1
  case csi // = 2
  case ip // = 3
  case ros2 // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .usb
    case 2: self = .csi
    case 3: self = .ip
    case 4: self = .ros2
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .usb: return 1
    case .csi: return 2
    case .ip: return 3
    case .ros2: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Wendy_Agent_Services_V1_VideoTransport] = [
    .unknown,
    .usb,
    .csi,
    .ip,
    .ros2,
  ]

}

public nonisolated enum Wendy_Agent_Services_V1_VideoCodec: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// raw H.264 annexb NAL units (default)
  case h264 // = 0

  /// VP8 inside a WebM container (webmmux streamable=true)
  case vp8 // = 1

  /// one uncompressed capture frame per message; layout in VideoFrame.raw_format
  case raw // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .h264
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .h264
    case 1: self = .vp8
    case 2: self = .raw
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .h264: return 0
    case .vp8: return 1
    case .raw: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Wendy_Agent_Services_V1_VideoCodec] = [
    .h264,
    .vp8,
    .raw,
  ]

}

public nonisolated struct Wendy_Agent_Services_V1_VideoDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// numeric suffix of /dev/videoN; network cameras use the reserved 200-255 band
  public var id: UInt32 = 0

  /// human-readable name from sysfs, or the model for network cameras
  public var name: String = String()

  /// e.g. "/dev/video0"; empty for a network camera with no loopback node
  public var path: String = String()

  /// interface (csi, usb, ip, unknown)
  public var transport: Wendy_Agent_Services_V1_VideoTransport = .unknown

  /// kernel driver name from sysfs (e.g. "uvcvideo", "tegra-capture-vi"); empty if unknown
  public var driver: String = String()

  /// libcamera camera-name; empty when libcamera enumeration unavailable or ambiguous
  public var libcameraID: String = String()

  /// network camera address, e.g. "10.98.0.50"; empty for local cameras
  public var address: String = String()

  /// model reported by discovery, e.g. "RLC-520A"
  public var model: String = String()

  /// stable identity for network cameras; empty for local cameras
  public var mac: String = String()

  /// the agent holds a login for this camera
  public var hasCredentials_p: Bool = false

  /// the most recent probe reached this camera
  public var online: Bool = false

  /// ROS 2 image topic, e.g. "/camera/image_raw"; empty for other transports
  public var topic: String = String()

  /// Stable identity for a LOCAL camera, the counterpart of `mac` above, and
  /// the name to pass to StreamVideoRequest.stable_id.
  ///
  /// `id` and `path` are the kernel's enumeration order, which is a property
  /// of the boot and not of the camera: replugging or a reboot can renumber
  /// /dev/videoN, and a caller that pinned a number then silently streams a
  /// different camera. `name` and `driver` only identify the MODEL, so they
  /// cannot separate two cameras of the same type.
  ///
  /// One camera has one stable_id. The value carries the scheme it came from,
  /// because the two names udev publishes are not equally durable:
  ///
  ///   by-id:<name>    vendor + product + serial; survives a reboot AND a
  ///                   move to another USB port. Reported whenever udev has
  ///                   one.
  ///   by-path:<name>  the USB port topology; survives a reboot but NOT a
  ///                   move. Reported only when there is no by-id name --
  ///                   two same-model cameras sharing a factory serial
  ///                   collide on a single by-id link, and the camera that
  ///                   loses it has nothing else that separates the two.
  ///
  /// Empty when the device has no /dev/v4l entry -- CSI and network cameras,
  /// or a kernel without the udev symlinks.
  public var stableID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_ListVideoDevicesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_ListVideoDevicesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var devices: [Wendy_Agent_Services_V1_VideoDevice] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_StreamVideoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// numeric suffix N in /dev/videoN; 0 maps to /dev/video0
  public var deviceID: UInt32 = 0

  /// For local cameras width/height/framerate configure capture. For network
  /// cameras the camera decides its own format, so width only selects which of
  /// its streams to open (sub or main) and height/framerate are ignored.
  public var width: UInt32 = 0

  /// pixels; 0 = device default
  public var height: UInt32 = 0

  /// fps; 0 = device default
  public var framerate: UInt32 = 0

  /// The requested delivery codec. The default, VIDEO_CODEC_H264 (0), delivers
  /// encoded video exactly as before this field existed. VIDEO_CODEC_RAW instead
  /// delivers the camera's capture frames uncompressed: every VideoFrame then
  /// carries exactly one complete frame with codec VIDEO_CODEC_RAW and raw_format
  /// describing its layout. Other subscribers of the same camera keep receiving
  /// encoded video: raw and encoded consumers share one capture, so an analytic
  /// reader (a thermal module's per-pixel temperatures, for instance) and a
  /// viewer no longer compete for the node.
  ///
  /// VIDEO_CODEC_RAW is offered only for local cameras the agent captures in a
  /// raw pixel format; a camera streaming MJPEG or native H.264, a network
  /// camera, or one shared through PipeWire has no raw frames to give, and the
  /// request fails with FailedPrecondition (reason RAW_UNAVAILABLE) rather than
  /// waiting forever. A codec the agent cannot produce for a camera is refused
  /// the same way rather than silently downgraded.
  public var codec: Wendy_Agent_Services_V1_VideoCodec = .h264

  /// Address the camera by the stable_id ListVideoDevices reported for it,
  /// scheme tag included, instead of by device_id.
  ///
  /// When set this WINS over device_id and is resolved at request time. That
  /// is the point: the number is resolved when the stream is opened rather
  /// than baked into a config that outlives the boot it was written on.
  ///
  /// A "by-path:" name resolves too, even for a camera whose reported
  /// stable_id is a "by-id:" one: pinning a stream to a physical port is a
  /// legitimate thing to ask for, as long as the caller asks for it rather
  /// than inheriting it.
  ///
  /// No match is an error, deliberately. Falling back to device_id would
  /// stream whatever the kernel happened to put at that number, which is the
  /// silent-wrong-camera failure this field exists to remove.
  public var stableID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Credentials for a network camera. Stored on the device, never returned by any
/// RPC: listings report only has_credentials.
public nonisolated struct Wendy_Agent_Services_V1_SetCameraCredentialsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: UInt32 = 0

  public var username: String = String()

  public var password: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_SetCameraCredentialsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_ForgetCameraRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_ForgetCameraResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_RefreshCamerasRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_RefreshCamerasResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var devices: [Wendy_Agent_Services_V1_VideoDevice] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// TestCameraCredentials validates a network camera's stored login by probing
/// its RTSP port directly, without starting a capture pipeline. Local (V4L2)
/// device IDs are rejected: there is nothing to validate for them.
public nonisolated struct Wendy_Agent_Services_V1_TestCameraCredentialsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_TestCameraCredentialsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Wendy_Agent_Services_V1_TestCameraCredentialsResponse.Result = .unspecified

  /// the address probed, e.g. "10.98.0.50"
  public var address: String = String()

  /// human-readable outcome; camera credentials are redacted
  public var detail: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Result: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0

    /// the camera accepted the stored credentials
    case ok // = 1

    /// the camera rejected the stored credentials
    case authFailed // = 2

    /// the camera's RTSP port could not be reached
    case unreachable // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .ok
      case 2: self = .authFailed
      case 3: self = .unreachable
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .ok: return 1
      case .authFailed: return 2
      case .unreachable: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Wendy_Agent_Services_V1_TestCameraCredentialsResponse.Result] = [
      .unspecified,
      .ok,
      .authFailed,
      .unreachable,
    ]

  }

  public init() {}
}

/// RawFormat describes the bytes of a VIDEO_CODEC_RAW frame: the V4L2 pixel
/// format the camera was captured in and the geometry needed to index it. It is
/// the camera's own layout, untouched — for a thermal module whose mode stacks
/// metadata rows onto the picture, those rows are included.
public nonisolated struct Wendy_Agent_Services_V1_RawFormat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// pixels
  public var width: UInt32 = 0

  /// rows, including any non-picture rows the mode carries
  public var height: UInt32 = 0

  /// V4L2 pixel format, e.g. "YUYV" (2 bytes per pixel)
  public var fourcc: String = String()

  /// stride; data is exactly bytes_per_line * height bytes
  public var bytesPerLine: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_VideoFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// chunk of encoded video; concatenate chunks in order; format described by codec. For VIDEO_CODEC_RAW, one whole frame.
  public var data: Data = Data()

  /// wall-clock timestamp in nanoseconds
  public var timestampNs: UInt64 = 0

  /// codec used; default 0 = H264
  public var codec: Wendy_Agent_Services_V1_VideoCodec = .h264

  /// set on VIDEO_CODEC_RAW frames only
  public var rawFormat: Wendy_Agent_Services_V1_RawFormat {
    get {_rawFormat ?? Wendy_Agent_Services_V1_RawFormat()}
    set {_rawFormat = newValue}
  }
  /// Returns true if `rawFormat` has been explicitly set.
  public var hasRawFormat: Bool {self._rawFormat != nil}
  /// Clears the value of `rawFormat`. Subsequent reads from it will return its default value.
  public mutating func clearRawFormat() {self._rawFormat = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rawFormat: Wendy_Agent_Services_V1_RawFormat? = nil
}

/// A tunable V4L2 control on a local camera -- exposure, gain, white balance and
/// the like. The agent owns the /dev/videoN node (StreamVideo multiplexes it),
/// so it is the only place these can be set to stick: a second process cannot,
/// and a setting made out of band is lost the next time the pipeline reopens the
/// device. The motivating case is a scene the camera's auto-exposure gets wrong
/// -- a flame or lamp that blows out to white -- where forcing manual exposure
/// keeps the highlight from clipping.
public nonisolated struct Wendy_Agent_Services_V1_CameraControl: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// stable slug, e.g. "auto_exposure", "exposure_time_absolute", "brightness", "gain", "backlight_compensation"
  public var name: String = String()

  /// the driver's current value
  public var value: Int32 = 0

  /// inclusive
  public var minimum: Int32 = 0

  /// inclusive
  public var maximum: Int32 = 0

  public var step: Int32 = 0

  public var defaultValue: Int32 = 0

  /// false when the driver reports it read-only or disabled right now
  public var mutable: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// What a caller ASKS for. Deliberately not CameraControl: that message answers
/// "what does the driver report", and five of its seven fields are the driver's
/// answer rather than the caller's request. One message doing both jobs means a
/// writer fills in minimum/maximum/step/default/mutable that the server then
/// ignores -- the comments carry the contract instead of the types.
public nonisolated struct Wendy_Agent_Services_V1_CameraControlSetting: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var value: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_GetCameraControlsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// numeric suffix N in /dev/videoN; the reserved network-camera band is rejected
  public var deviceID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_GetCameraControlsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var controls: [Wendy_Agent_Services_V1_CameraControl] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_SetCameraControlsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: UInt32 = 0

  public var controls: [Wendy_Agent_Services_V1_CameraControlSetting] = []

  /// Re-apply these whenever the capture pipeline reopens the device, and
  /// across agent restarts, so a stream reconnect or a reboot does not revert
  /// to the firmware default. When false the values are applied once, now.
  public var persist: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_SetCameraControlsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var results: [Wendy_Agent_Services_V1_CameraControlResult] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Put controls back to the driver's own defaults and STOP persisting them.
///
/// A separate RPC rather than a flag on Set, because it is a different verb:
/// Set says "make it this", Reset says "forget I ever said anything". It changes
/// the persisted state as well as the value, so a caller that models it as
/// "set to the default" would leave the control pinned to that default forever
/// -- which is the thing being undone.
///
/// The default comes from the driver (QUERYCTRL), so the camera answers rather
/// than the caller having to know.
public nonisolated struct Wendy_Agent_Services_V1_ResetCameraControlsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: UInt32 = 0

  /// Controls to reset by name. EMPTY MEANS EVERY PERSISTED CONTROL, which is
  /// the useful case after a tuning session went wrong: the caller wants the
  /// camera back as it shipped and should not have to enumerate what it
  /// changed to get there.
  public var names: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_ResetCameraControlsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var results: [Wendy_Agent_Services_V1_CameraControlResult] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Wendy_Agent_Services_V1_CameraControlResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var applied: Bool = false

  /// when not applied, why -- e.g. "unknown control" or the errno text
  public var detail: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "wendy.agent.services.v1"

nonisolated extension Wendy_Agent_Services_V1_VideoTransport: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VIDEO_TRANSPORT_UNKNOWN\0\u{1}VIDEO_TRANSPORT_USB\0\u{1}VIDEO_TRANSPORT_CSI\0\u{1}VIDEO_TRANSPORT_IP\0\u{1}VIDEO_TRANSPORT_ROS2\0")
}

nonisolated extension Wendy_Agent_Services_V1_VideoCodec: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VIDEO_CODEC_H264\0\u{1}VIDEO_CODEC_VP8\0\u{1}VIDEO_CODEC_RAW\0")
}

nonisolated extension Wendy_Agent_Services_V1_VideoDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoDevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}path\0\u{1}transport\0\u{1}driver\0\u{3}libcamera_id\0\u{1}address\0\u{1}model\0\u{1}mac\0\u{3}has_credentials\0\u{1}online\0\u{1}topic\0\u{3}stable_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.transport) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.driver) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.libcameraID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.mac) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.hasCredentials_p) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.online) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.topic) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.stableID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 3)
    }
    if self.transport != .unknown {
      try visitor.visitSingularEnumField(value: self.transport, fieldNumber: 4)
    }
    if !self.driver.isEmpty {
      try visitor.visitSingularStringField(value: self.driver, fieldNumber: 5)
    }
    if !self.libcameraID.isEmpty {
      try visitor.visitSingularStringField(value: self.libcameraID, fieldNumber: 6)
    }
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 7)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 8)
    }
    if !self.mac.isEmpty {
      try visitor.visitSingularStringField(value: self.mac, fieldNumber: 9)
    }
    if self.hasCredentials_p != false {
      try visitor.visitSingularBoolField(value: self.hasCredentials_p, fieldNumber: 10)
    }
    if self.online != false {
      try visitor.visitSingularBoolField(value: self.online, fieldNumber: 11)
    }
    if !self.topic.isEmpty {
      try visitor.visitSingularStringField(value: self.topic, fieldNumber: 12)
    }
    if !self.stableID.isEmpty {
      try visitor.visitSingularStringField(value: self.stableID, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_VideoDevice, rhs: Wendy_Agent_Services_V1_VideoDevice) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.path != rhs.path {return false}
    if lhs.transport != rhs.transport {return false}
    if lhs.driver != rhs.driver {return false}
    if lhs.libcameraID != rhs.libcameraID {return false}
    if lhs.address != rhs.address {return false}
    if lhs.model != rhs.model {return false}
    if lhs.mac != rhs.mac {return false}
    if lhs.hasCredentials_p != rhs.hasCredentials_p {return false}
    if lhs.online != rhs.online {return false}
    if lhs.topic != rhs.topic {return false}
    if lhs.stableID != rhs.stableID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_ListVideoDevicesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListVideoDevicesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_ListVideoDevicesRequest, rhs: Wendy_Agent_Services_V1_ListVideoDevicesRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_ListVideoDevicesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListVideoDevicesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}devices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.devices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.devices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.devices, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_ListVideoDevicesResponse, rhs: Wendy_Agent_Services_V1_ListVideoDevicesResponse) -> Bool {
    if lhs.devices != rhs.devices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_StreamVideoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamVideoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{1}width\0\u{1}height\0\u{1}framerate\0\u{1}codec\0\u{3}stable_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.framerate) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.codec) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.stableID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 2)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 3)
    }
    if self.framerate != 0 {
      try visitor.visitSingularUInt32Field(value: self.framerate, fieldNumber: 4)
    }
    if self.codec != .h264 {
      try visitor.visitSingularEnumField(value: self.codec, fieldNumber: 5)
    }
    if !self.stableID.isEmpty {
      try visitor.visitSingularStringField(value: self.stableID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_StreamVideoRequest, rhs: Wendy_Agent_Services_V1_StreamVideoRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.framerate != rhs.framerate {return false}
    if lhs.codec != rhs.codec {return false}
    if lhs.stableID != rhs.stableID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_SetCameraCredentialsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetCameraCredentialsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{1}username\0\u{1}password\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.username) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.password) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    if !self.username.isEmpty {
      try visitor.visitSingularStringField(value: self.username, fieldNumber: 2)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_SetCameraCredentialsRequest, rhs: Wendy_Agent_Services_V1_SetCameraCredentialsRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.username != rhs.username {return false}
    if lhs.password != rhs.password {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_SetCameraCredentialsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetCameraCredentialsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_SetCameraCredentialsResponse, rhs: Wendy_Agent_Services_V1_SetCameraCredentialsResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_ForgetCameraRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ForgetCameraRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_ForgetCameraRequest, rhs: Wendy_Agent_Services_V1_ForgetCameraRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_ForgetCameraResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ForgetCameraResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_ForgetCameraResponse, rhs: Wendy_Agent_Services_V1_ForgetCameraResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_RefreshCamerasRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RefreshCamerasRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_RefreshCamerasRequest, rhs: Wendy_Agent_Services_V1_RefreshCamerasRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_RefreshCamerasResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RefreshCamerasResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}devices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.devices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.devices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.devices, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_RefreshCamerasResponse, rhs: Wendy_Agent_Services_V1_RefreshCamerasResponse) -> Bool {
    if lhs.devices != rhs.devices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_TestCameraCredentialsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TestCameraCredentialsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_TestCameraCredentialsRequest, rhs: Wendy_Agent_Services_V1_TestCameraCredentialsRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_TestCameraCredentialsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TestCameraCredentialsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{1}address\0\u{1}detail\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.result) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.detail) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.result != .unspecified {
      try visitor.visitSingularEnumField(value: self.result, fieldNumber: 1)
    }
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 2)
    }
    if !self.detail.isEmpty {
      try visitor.visitSingularStringField(value: self.detail, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_TestCameraCredentialsResponse, rhs: Wendy_Agent_Services_V1_TestCameraCredentialsResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.address != rhs.address {return false}
    if lhs.detail != rhs.detail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_TestCameraCredentialsResponse.Result: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESULT_UNSPECIFIED\0\u{1}RESULT_OK\0\u{1}RESULT_AUTH_FAILED\0\u{1}RESULT_UNREACHABLE\0")
}

nonisolated extension Wendy_Agent_Services_V1_RawFormat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RawFormat"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}width\0\u{1}height\0\u{1}fourcc\0\u{3}bytes_per_line\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fourcc) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.bytesPerLine) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 2)
    }
    if !self.fourcc.isEmpty {
      try visitor.visitSingularStringField(value: self.fourcc, fieldNumber: 3)
    }
    if self.bytesPerLine != 0 {
      try visitor.visitSingularUInt32Field(value: self.bytesPerLine, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_RawFormat, rhs: Wendy_Agent_Services_V1_RawFormat) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.fourcc != rhs.fourcc {return false}
    if lhs.bytesPerLine != rhs.bytesPerLine {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_VideoFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoFrame"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{3}timestamp_ns\0\u{1}codec\0\u{3}raw_format\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.timestampNs) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.codec) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._rawFormat) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    if self.timestampNs != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestampNs, fieldNumber: 2)
    }
    if self.codec != .h264 {
      try visitor.visitSingularEnumField(value: self.codec, fieldNumber: 3)
    }
    try { if let v = self._rawFormat {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_VideoFrame, rhs: Wendy_Agent_Services_V1_VideoFrame) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.timestampNs != rhs.timestampNs {return false}
    if lhs.codec != rhs.codec {return false}
    if lhs._rawFormat != rhs._rawFormat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_CameraControl: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CameraControl"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0\u{1}minimum\0\u{1}maximum\0\u{1}step\0\u{3}default_value\0\u{1}mutable\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.value) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.minimum) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.maximum) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.step) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.defaultValue) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.mutable) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularInt32Field(value: self.value, fieldNumber: 2)
    }
    if self.minimum != 0 {
      try visitor.visitSingularInt32Field(value: self.minimum, fieldNumber: 3)
    }
    if self.maximum != 0 {
      try visitor.visitSingularInt32Field(value: self.maximum, fieldNumber: 4)
    }
    if self.step != 0 {
      try visitor.visitSingularInt32Field(value: self.step, fieldNumber: 5)
    }
    if self.defaultValue != 0 {
      try visitor.visitSingularInt32Field(value: self.defaultValue, fieldNumber: 6)
    }
    if self.mutable != false {
      try visitor.visitSingularBoolField(value: self.mutable, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_CameraControl, rhs: Wendy_Agent_Services_V1_CameraControl) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.minimum != rhs.minimum {return false}
    if lhs.maximum != rhs.maximum {return false}
    if lhs.step != rhs.step {return false}
    if lhs.defaultValue != rhs.defaultValue {return false}
    if lhs.mutable != rhs.mutable {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_CameraControlSetting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CameraControlSetting"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularInt32Field(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_CameraControlSetting, rhs: Wendy_Agent_Services_V1_CameraControlSetting) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_GetCameraControlsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetCameraControlsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_GetCameraControlsRequest, rhs: Wendy_Agent_Services_V1_GetCameraControlsRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_GetCameraControlsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetCameraControlsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}controls\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.controls) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.controls.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.controls, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_GetCameraControlsResponse, rhs: Wendy_Agent_Services_V1_GetCameraControlsResponse) -> Bool {
    if lhs.controls != rhs.controls {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_SetCameraControlsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetCameraControlsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{1}controls\0\u{1}persist\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.controls) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.persist) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    if !self.controls.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.controls, fieldNumber: 2)
    }
    if self.persist != false {
      try visitor.visitSingularBoolField(value: self.persist, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_SetCameraControlsRequest, rhs: Wendy_Agent_Services_V1_SetCameraControlsRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.controls != rhs.controls {return false}
    if lhs.persist != rhs.persist {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_SetCameraControlsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetCameraControlsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}results\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_SetCameraControlsResponse, rhs: Wendy_Agent_Services_V1_SetCameraControlsResponse) -> Bool {
    if lhs.results != rhs.results {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_ResetCameraControlsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResetCameraControlsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{1}names\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deviceID) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.names) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deviceID != 0 {
      try visitor.visitSingularUInt32Field(value: self.deviceID, fieldNumber: 1)
    }
    if !self.names.isEmpty {
      try visitor.visitRepeatedStringField(value: self.names, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_ResetCameraControlsRequest, rhs: Wendy_Agent_Services_V1_ResetCameraControlsRequest) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.names != rhs.names {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_ResetCameraControlsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResetCameraControlsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}results\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_ResetCameraControlsResponse, rhs: Wendy_Agent_Services_V1_ResetCameraControlsResponse) -> Bool {
    if lhs.results != rhs.results {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Wendy_Agent_Services_V1_CameraControlResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CameraControlResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}applied\0\u{1}detail\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.applied) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.detail) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.applied != false {
      try visitor.visitSingularBoolField(value: self.applied, fieldNumber: 2)
    }
    if !self.detail.isEmpty {
      try visitor.visitSingularStringField(value: self.detail, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Wendy_Agent_Services_V1_CameraControlResult, rhs: Wendy_Agent_Services_V1_CameraControlResult) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.applied != rhs.applied {return false}
    if lhs.detail != rhs.detail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
