// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: cloud/apps.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

public import GRPCCore
public import GRPCProtobuf

// MARK: - wendycloud.v1.AppService

/// Namespace containing generated types for the "wendycloud.v1.AppService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Wendycloud_V1_AppService: Sendable {
    /// Service descriptor for the "wendycloud.v1.AppService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "UpsertApp" metadata.
        public enum UpsertApp: Sendable {
            /// Request type for "UpsertApp".
            public typealias Input = Wendycloud_V1_UpsertAppRequest
            /// Response type for "UpsertApp".
            public typealias Output = Wendycloud_V1_App
            /// Descriptor for "UpsertApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService"),
                method: "UpsertApp",
                type: .unary
            )
        }
        /// Namespace for "GetApp" metadata.
        public enum GetApp: Sendable {
            /// Request type for "GetApp".
            public typealias Input = Wendycloud_V1_GetAppRequest
            /// Response type for "GetApp".
            public typealias Output = Wendycloud_V1_App
            /// Descriptor for "GetApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService"),
                method: "GetApp",
                type: .unary
            )
        }
        /// Namespace for "UpdateApp" metadata.
        public enum UpdateApp: Sendable {
            /// Request type for "UpdateApp".
            public typealias Input = Wendycloud_V1_UpdateAppRequest
            /// Response type for "UpdateApp".
            public typealias Output = Wendycloud_V1_App
            /// Descriptor for "UpdateApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService"),
                method: "UpdateApp",
                type: .unary
            )
        }
        /// Namespace for "DeleteApp" metadata.
        public enum DeleteApp: Sendable {
            /// Request type for "DeleteApp".
            public typealias Input = Wendycloud_V1_DeleteAppRequest
            /// Response type for "DeleteApp".
            public typealias Output = Wendycloud_V1_DeleteAppResponse
            /// Descriptor for "DeleteApp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService"),
                method: "DeleteApp",
                type: .unary
            )
        }
        /// Namespace for "ListApps" metadata.
        public enum ListApps: Sendable {
            /// Request type for "ListApps".
            public typealias Input = Wendycloud_V1_ListAppsRequest
            /// Response type for "ListApps".
            public typealias Output = Wendycloud_V1_ListAppsResponse
            /// Descriptor for "ListApps".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService"),
                method: "ListApps",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "wendycloud.v1.AppService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            UpsertApp.descriptor,
            GetApp.descriptor,
            UpdateApp.descriptor,
            DeleteApp.descriptor,
            ListApps.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "wendycloud.v1.AppService" service.
    public static let wendycloud_v1_AppService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v1.AppService")
}

// MARK: wendycloud.v1.AppService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService {
    /// Streaming variant of the service protocol for the "wendycloud.v1.AppService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where the RPC expects only a single
    /// request or response message, you are responsible for ensuring your implementation
    /// maintains this invariant.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "UpsertApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendycloud_V1_UpsertAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendycloud_V1_App` messages.
        func upsertApp(
            request: GRPCCore.StreamingServerRequest<Wendycloud_V1_UpsertAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_App>

        /// Handle the "GetApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendycloud_V1_GetAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendycloud_V1_App` messages.
        func getApp(
            request: GRPCCore.StreamingServerRequest<Wendycloud_V1_GetAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_App>

        /// Handle the "UpdateApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendycloud_V1_UpdateAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendycloud_V1_App` messages.
        func updateApp(
            request: GRPCCore.StreamingServerRequest<Wendycloud_V1_UpdateAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_App>

        /// Handle the "DeleteApp" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendycloud_V1_DeleteAppRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendycloud_V1_DeleteAppResponse` messages.
        func deleteApp(
            request: GRPCCore.StreamingServerRequest<Wendycloud_V1_DeleteAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_DeleteAppResponse>

        /// Handle the "ListApps" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendycloud_V1_ListAppsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendycloud_V1_ListAppsResponse` messages.
        func listApps(
            request: GRPCCore.StreamingServerRequest<Wendycloud_V1_ListAppsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_ListAppsResponse>
    }

    /// Service protocol for the "wendycloud.v1.AppService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Wendycloud_V1_AppService.StreamingServiceProtocol {
        /// Handle the "UpsertApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_UpsertAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendycloud_V1_App` message.
        func upsertApp(
            request: GRPCCore.ServerRequest<Wendycloud_V1_UpsertAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_App>

        /// Handle the "GetApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_GetAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendycloud_V1_App` message.
        func getApp(
            request: GRPCCore.ServerRequest<Wendycloud_V1_GetAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_App>

        /// Handle the "UpdateApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_UpdateAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendycloud_V1_App` message.
        func updateApp(
            request: GRPCCore.ServerRequest<Wendycloud_V1_UpdateAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_App>

        /// Handle the "DeleteApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_DeleteAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendycloud_V1_DeleteAppResponse` message.
        func deleteApp(
            request: GRPCCore.ServerRequest<Wendycloud_V1_DeleteAppRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_DeleteAppResponse>

        /// Handle the "ListApps" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_ListAppsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendycloud_V1_ListAppsResponse` message.
        func listApps(
            request: GRPCCore.ServerRequest<Wendycloud_V1_ListAppsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_ListAppsResponse>
    }

    /// Simple service protocol for the "wendycloud.v1.AppService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Wendycloud_V1_AppService.ServiceProtocol {
        /// Handle the "UpsertApp" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendycloud_V1_UpsertAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendycloud_V1_App` to respond with.
        func upsertApp(
            request: Wendycloud_V1_UpsertAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendycloud_V1_App

        /// Handle the "GetApp" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendycloud_V1_GetAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendycloud_V1_App` to respond with.
        func getApp(
            request: Wendycloud_V1_GetAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendycloud_V1_App

        /// Handle the "UpdateApp" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendycloud_V1_UpdateAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendycloud_V1_App` to respond with.
        func updateApp(
            request: Wendycloud_V1_UpdateAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendycloud_V1_App

        /// Handle the "DeleteApp" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendycloud_V1_DeleteAppRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendycloud_V1_DeleteAppResponse` to respond with.
        func deleteApp(
            request: Wendycloud_V1_DeleteAppRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendycloud_V1_DeleteAppResponse

        /// Handle the "ListApps" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendycloud_V1_ListAppsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendycloud_V1_ListAppsResponse` to respond with.
        func listApps(
            request: Wendycloud_V1_ListAppsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendycloud_V1_ListAppsResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Wendycloud_V1_AppService.Method.UpsertApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_UpsertAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_App>(),
            handler: { request, context in
                try await self.upsertApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Wendycloud_V1_AppService.Method.GetApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_GetAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_App>(),
            handler: { request, context in
                try await self.getApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Wendycloud_V1_AppService.Method.UpdateApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_UpdateAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_App>(),
            handler: { request, context in
                try await self.updateApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Wendycloud_V1_AppService.Method.DeleteApp.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_DeleteAppRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_DeleteAppResponse>(),
            handler: { request, context in
                try await self.deleteApp(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Wendycloud_V1_AppService.Method.ListApps.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_ListAppsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_ListAppsResponse>(),
            handler: { request, context in
                try await self.listApps(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService.ServiceProtocol {
    public func upsertApp(
        request: GRPCCore.StreamingServerRequest<Wendycloud_V1_UpsertAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_App> {
        let response = try await self.upsertApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func getApp(
        request: GRPCCore.StreamingServerRequest<Wendycloud_V1_GetAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_App> {
        let response = try await self.getApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updateApp(
        request: GRPCCore.StreamingServerRequest<Wendycloud_V1_UpdateAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_App> {
        let response = try await self.updateApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func deleteApp(
        request: GRPCCore.StreamingServerRequest<Wendycloud_V1_DeleteAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_DeleteAppResponse> {
        let response = try await self.deleteApp(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func listApps(
        request: GRPCCore.StreamingServerRequest<Wendycloud_V1_ListAppsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V1_ListAppsResponse> {
        let response = try await self.listApps(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService.SimpleServiceProtocol {
    public func upsertApp(
        request: GRPCCore.ServerRequest<Wendycloud_V1_UpsertAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_App> {
        return GRPCCore.ServerResponse<Wendycloud_V1_App>(
            message: try await self.upsertApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func getApp(
        request: GRPCCore.ServerRequest<Wendycloud_V1_GetAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_App> {
        return GRPCCore.ServerResponse<Wendycloud_V1_App>(
            message: try await self.getApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updateApp(
        request: GRPCCore.ServerRequest<Wendycloud_V1_UpdateAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_App> {
        return GRPCCore.ServerResponse<Wendycloud_V1_App>(
            message: try await self.updateApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func deleteApp(
        request: GRPCCore.ServerRequest<Wendycloud_V1_DeleteAppRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_DeleteAppResponse> {
        return GRPCCore.ServerResponse<Wendycloud_V1_DeleteAppResponse>(
            message: try await self.deleteApp(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func listApps(
        request: GRPCCore.ServerRequest<Wendycloud_V1_ListAppsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendycloud_V1_ListAppsResponse> {
        return GRPCCore.ServerResponse<Wendycloud_V1_ListAppsResponse>(
            message: try await self.listApps(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: wendycloud.v1.AppService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService {
    /// Generated client protocol for the "wendycloud.v1.AppService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "UpsertApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_UpsertAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_UpsertAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_App` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func upsertApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_UpsertAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_UpsertAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_App>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_GetAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_GetAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_App` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func getApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_GetAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_GetAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_App>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_UpdateAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_UpdateAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_App` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func updateApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_UpdateAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_UpdateAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_App>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_DeleteAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_DeleteAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_DeleteAppResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_DeleteAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_DeleteAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_DeleteAppResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_DeleteAppResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListApps" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_ListAppsRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_ListAppsRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_ListAppsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func listApps<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_ListAppsRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_ListAppsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_ListAppsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_ListAppsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "wendycloud.v1.AppService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "UpsertApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_UpsertAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_UpsertAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_App` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func upsertApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_UpsertAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_UpsertAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_App>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendycloud_V1_AppService.Method.UpsertApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_GetAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_GetAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_App` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func getApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_GetAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_GetAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_App>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendycloud_V1_AppService.Method.GetApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_UpdateAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_UpdateAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_App` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_UpdateAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_UpdateAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_App>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendycloud_V1_AppService.Method.UpdateApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteApp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_DeleteAppRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_DeleteAppRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_DeleteAppResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteApp<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_DeleteAppRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_DeleteAppRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_DeleteAppResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_DeleteAppResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendycloud_V1_AppService.Method.DeleteApp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListApps" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V1_ListAppsRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V1_ListAppsRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V1_ListAppsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func listApps<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V1_ListAppsRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V1_ListAppsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V1_ListAppsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_ListAppsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendycloud_V1_AppService.Method.ListApps.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService.ClientProtocol {
    /// Call the "UpsertApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendycloud_V1_UpsertAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func upsertApp<Result>(
        request: GRPCCore.ClientRequest<Wendycloud_V1_UpsertAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.upsertApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_UpsertAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_App>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendycloud_V1_GetAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func getApp<Result>(
        request: GRPCCore.ClientRequest<Wendycloud_V1_GetAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_GetAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_App>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendycloud_V1_UpdateAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateApp<Result>(
        request: GRPCCore.ClientRequest<Wendycloud_V1_UpdateAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_UpdateAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_App>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteApp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendycloud_V1_DeleteAppRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteApp<Result>(
        request: GRPCCore.ClientRequest<Wendycloud_V1_DeleteAppRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_DeleteAppResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteApp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_DeleteAppRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_DeleteAppResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListApps" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendycloud_V1_ListAppsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func listApps<Result>(
        request: GRPCCore.ClientRequest<Wendycloud_V1_ListAppsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_ListAppsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listApps(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V1_ListAppsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V1_ListAppsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V1_AppService.ClientProtocol {
    /// Call the "UpsertApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func upsertApp<Result>(
        _ message: Wendycloud_V1_UpsertAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendycloud_V1_UpsertAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.upsertApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func getApp<Result>(
        _ message: Wendycloud_V1_GetAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendycloud_V1_GetAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateApp<Result>(
        _ message: Wendycloud_V1_UpdateAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_App>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendycloud_V1_UpdateAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteApp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteApp<Result>(
        _ message: Wendycloud_V1_DeleteAppRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_DeleteAppResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendycloud_V1_DeleteAppRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteApp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListApps" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func listApps<Result>(
        _ message: Wendycloud_V1_ListAppsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V1_ListAppsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendycloud_V1_ListAppsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listApps(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}