FROM debian:bookworm-slim
COPY seed /seed
RUN cat /seed > /f1
RUN cat /seed > /f2
RUN cat /seed > /f3
RUN cat /seed > /f4
RUN cat /seed > /f5
RUN cat /seed > /f6
RUN cat /seed > /f7
RUN cat /seed > /f8
RUN cat /seed > /f9
RUN cat /seed > /f10
RUN cat /seed > /f11
RUN cat /seed > /f12
RUN cat /seed > /f13
RUN cat /seed > /f14
RUN cat /seed > /f15
RUN cat /seed > /f16
RUN cat /seed > /f17
RUN cat /seed > /f18
RUN cat /seed > /f19
RUN cat /seed > /f20
CMD ["sleep", "infinity"]
